name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - node.20-nu.latest/Dockerfile
      - node.20-nu.latest-extra/Dockerfile
      - .github/workflows/build-nu.yaml
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Default Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./node.20-nu.latest
          file: ./node.20-nu.latest/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            hustcer/debian-nu:latest
            hustcer/debian-nu:0.99-node.20.17.lts
            ghcr.io/hustcer/debian-nu:latest
            ghcr.io/hustcer/debian-nu:0.99-node.20.17.lts

      - name: Build and Push Extra Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./node.20-nu.latest-extra
          file: ./node.20-nu.latest-extra/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            hustcer/debian-nu:0.99-node.20.17-extra
            ghcr.io/hustcer/debian-nu:0.99-node.20.17-extra
