name: Build and Push Docker Node Image

on:
  push:
    branches:
      - main
    paths:
      - 'debian-node/Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: ./debian-node
          file: ./debian-node/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hustcer/debian-node:20.17-lts
            hustcer/debian-node:latest


