name: Build and Push Android Dev Image

on:
  push:
    branches:
      - main
    paths:
      - android-build/Dockerfile
      - .github/workflows/build-android.yaml
  workflow_dispatch:

jobs:
  build-and-push-android:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Login to Erda Registry
        uses: docker/login-action@v3
        with:
          registry: registry.erda.cloud
          password: ${{ secrets.ERDA_REGISTRY_TOKEN }}
          username: ${{ secrets.ERDA_REGISTRY_USERNAME }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./android-build
          file: ./android-build/Dockerfile
          platforms: linux/amd64
          tags: |
            hustcer/rn-builder:latest
            hustcer/rn-builder:android35-gradle8.10-jdk17-node20.18
            registry.erda.cloud/terp/rn-builder:latest
            registry.erda.cloud/terp/rn-builder:android35-gradle8.10-jdk17-node20.18
