name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'node.20-nu.latest/Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./node.20-nu.latest
          file: ./node.20-nu.latest/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hustcer/debian-nu:0.97-node.20.17.lts
            hustcer/debian-nu:latest
