name: Build and Push Android Dev Image

on:
  push:
    branches:
      - main
    paths:
      - android-build/Dockerfile
      - .github/workflows/build-android.yaml
  workflow_dispatch:

jobs:
  build-and-push-android:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: hustcer
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Erda Registry
        uses: docker/login-action@v3
        with:
          registry: erda-registry.cn-hangzhou.cr.aliyuncs.com
          password: ${{ secrets.ERDA_REGISTRY_TOKEN }}
          username: ${{ secrets.ERDA_REGISTRY_USERNAME }}

      # rc1: 8.10.2  rc0: 8.11.1 rc2: 7.6.4
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./android-build
          file: ./android-build/Dockerfile
          platforms: linux/amd64
          tags: |
            hustcer/rn-builder:latest
            hustcer/rn-builder:android35-gradle8.10-jdk17-node20.18
            ghcr.io/hustcer/rn-builder:latest
            ghcr.io/hustcer/rn-builder:android35-gradle8.10-jdk17-node20.18
            erda-registry.cn-hangzhou.cr.aliyuncs.com/terp/rn-builder:latest
            erda-registry.cn-hangzhou.cr.aliyuncs.com/terp/rn-builder:rc2
            erda-registry.cn-hangzhou.cr.aliyuncs.com/terp/rn-builder:android35-gradle8.10-jdk17-node20.18

  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build-and-push-android
    steps:
      - name: Delete all containers from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v4
        with:
          owner_type: user
          untagged_only: true
          package_name: 'rn-builder'
          repository_owner: 'hustcer'
          token: ${{ secrets.GHCR_TOKEN }}
          except_untagged_multiplatform: true
