name: Build and Push Nushell Binaries @ Debian

on:
  push:
    branches:
      - main
    paths:
      - debian-nushell/Dockerfile
      - .github/workflows/release-nu-debian.yaml
  workflow_dispatch:

jobs:
  build-and-push-Nu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Build and Push Debian Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./debian-nushell
          file: ./debian-nushell/Dockerfile
          platforms: linux/amd64,linux/arm64
          # platforms: linux/amd64,linux/arm64,linux/riscv64
          tags: |
            hustcer/nushell:0.98.0-bookworm
            hustcer/nushell:latest-bookworm
