name: Build and Push Nushell Binaries @ Alpine

on:
  push:
    branches:
      - main
    paths:
      - alpine-nushell/Dockerfile
      - .github/workflows/release-nu-alpine.yaml
  workflow_dispatch:

jobs:
  build-and-push-Nu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Alpine Image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: ./alpine-nushell
          file: ./alpine-nushell/Dockerfile
          tags: |
            hustcer/nushell:0.98.0
            hustcer/nushell:latest
            hustcer/nushell:0.98.0-alpine
            hustcer/nushell:latest-alpine
            ghcr.io/hustcer/nushell:0.98.0
            ghcr.io/hustcer/nushell:latest
            ghcr.io/hustcer/nushell:0.98.0-alpine
            ghcr.io/hustcer/nushell:latest-alpine
