name: Build and Push Nushell Binaries @ Debian

on:
  push:
    branches:
      - main
    paths:
      - debian-nushell/Dockerfile
      - .github/workflows/release-nu-debian.yaml
  workflow_dispatch:

jobs:
  build-and-push-Nu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set tag & labels for ${{ github.ref }}"
        run: |
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          else
          echo "DOCKER_TAG=snapshot" >> $GITHUB_ENV
          fi
          echo "BUILD_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
          echo "BUILD_DATE=2024-09-28T23:35:20Z" >> $GITHUB_ENV

      - name: Build and Push Debian Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./debian-nushell
          file: ./debian-nushell/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          # platforms: linux/amd64,linux/arm64,linux/riscv64
          build-args: |
            BUILD_REF=${{ env.BUILD_REF }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          tags: |
            hustcer/nushell:0.98.0-bookworm
            hustcer/nushell:latest-bookworm
            ghcr.io/hustcer/nushell:0.98.0-bookworm
            ghcr.io/hustcer/nushell:latest-bookworm
