name: Build and Push Nushell Binaries @ Alpine

on:
  push:
    branches:
      - main
    paths:
      - alpine-nushell/Dockerfile
      - .github/workflows/release-nu-alpine.yaml
  workflow_dispatch:

jobs:
  build-and-push-Nu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # date now | format date "%Y-%m-%dT%H:%M:%SZ"
      - name: "Set tag & labels for ${{ github.ref }}"
        run: |
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          else
          echo "DOCKER_TAG=snapshot" >> $GITHUB_ENV
          fi
          echo "BUILD_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
          echo "BUILD_DATE=2024-09-28T23:35:20Z" >> $GITHUB_ENV

      - name: Build and Push Alpine Image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: ./alpine-nushell
          file: ./alpine-nushell/Dockerfile
          build-args: |
            BUILD_REF=${{ env.BUILD_REF }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          tags: |
            hustcer/nushell:0.98.0
            hustcer/nushell:latest
            hustcer/nushell:0.98.0-alpine
            hustcer/nushell:latest-alpine
            ghcr.io/hustcer/nushell:0.98.0
            ghcr.io/hustcer/nushell:latest
            ghcr.io/hustcer/nushell:0.98.0-alpine
            ghcr.io/hustcer/nushell:latest-alpine
