name: Build and Push Rust Cross Build Image for FreeBSD

on:
  push:
    branches:
      - main
    paths:
      - rust-cross-freebsd/*.sh
      - rust-cross-freebsd/*.nu
      - rust-cross-freebsd/Dockerfile
      - .github/workflows/rust-cross-freebsd.yaml
  workflow_dispatch:

jobs:
  build-and-push-Nu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Build and Push Rust Cross Build Image for FreeBSD
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./rust-cross-freebsd
          file: ./rust-cross-freebsd/Dockerfile
          platforms: linux/amd64
          tags: |
            hustcer/rust-cross-freebsd:13.4-rust-1.81.0
            hustcer/rust-cross-freebsd:latest
